### ISSUE TITLE
PyPlot Fails to Precompile on v0.6

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaPy/PyPlot.jl#251]
``` julia
julia> using PyPlot
INFO: Precompiling module Conda.
INFO: Recompiling stale cache file C:\Users\Chris\.julia\lib\v0.6\PyPlot.ji for module PyPlot.
C:\Users\Chris\.julia\v0.6\Conda\deps\usr\lib\site-packages\matplotlib\__init__.py:1357: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
ERROR: InitError: PyError (:PyImport_ImportModule) <class 'ImportError'>
ImportError("cannot import name 'QtCore'",)
  File "C:\Users\Chris\.julia\v0.6\Conda\deps\usr\lib\site-packages\matplotlib\pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "C:\Users\Chris\.julia\v0.6\Conda\deps\usr\lib\site-packages\matplotlib\backends\__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "C:\Users\Chris\.julia\v0.6\Conda\deps\usr\lib\site-packages\matplotlib\backends\backend_qt4agg.py", line 18, in <module>
    from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
  File "C:\Users\Chris\.julia\v0.6\Conda\deps\usr\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 16, in <module>
    from .backend_qt5 import QtCore
  File "C:\Users\Chris\.julia\v0.6\Conda\deps\usr\lib\site-packages\matplotlib\backends\backend_qt5.py", line 31, in <module>
    from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
  File "C:\Users\Chris\.julia\v0.6\Conda\deps\usr\lib\site-packages\matplotlib\backends\qt_compat.py", line 137, in <module>
    from PyQt4 import QtCore, QtGui

 in pyerr_check at C:\Users\Chris\.julia\v0.6\PyCall\src\exception.jl:56 [inlined]
 in pyerr_check at C:\Users\Chris\.julia\v0.6\PyCall\src\exception.jl:61 [inlined]
 in macro expansion at C:\Users\Chris\.julia\v0.6\PyCall\src\exception.jl:79 [inlined]
 in pyimport(::String) at C:\Users\Chris\.julia\v0.6\PyCall\src\PyCall.jl:387
 in __init__() at C:\Users\Chris\.julia\v0.6\PyPlot\src\PyPlot.jl:235
 in _include_from_serialized(::String) at .\loading.jl:150
 in _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at .\loading.jl:187
 in require(::Symbol) at .\loading.jl:425
during initialization of module PyPlot
```

This is on v0.6, with master for PyPlot, Conda, and PyCall, with the automated matplotlib installation.

**Comment by stevengj** [comment]
Can you try again with the latest master, now that #249 is merged?

**Comment by ChrisRackauckas** [comment]
Now it pre-compiles, but I get

```julia
INFO: Recompiling stale cache file C:\Users\Chris\.julia\lib\v0.6\PyPlot.ji for module PyPlot.
WARNING: No working GUI backend found for matplotlib.
```

**Comment by stevengj** [comment]
Okay, I can reproduce your problem.  cc @tkelman.

**Comment by stevengj** [comment]
Hmm, PyCall `pygui_works` still checks for the `PyQt4` library...

**Comment by stevengj** [comment]
For me, on MacOS, one problem seems to be a libpng conflict:
```jl
using PyCall
m = pyimport("matplotlib")
m["use"]("qt4agg")
pyimport("matplotlib.backends.backend_qt4agg")
```
gives
```
ERROR: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('dlopen(/Users/stevenj/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/_png.so, 2): Library not loaded: @rpath/libpng16.16.dylib\n  Referenced from: /Users/stevenj/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/_png.so\n  Reason: Incompatible library version: _png.so requires version 39.0.0 or later, but libpng16.16.dylib provides version 34.0.0',)
  File "/Users/stevenj/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 15, in <module>
    from matplotlib.figure import Figure
  File "/Users/stevenj/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/figure.py", line 36, in <module>
    from matplotlib.image import FigureImage
  File "/Users/stevenj/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/image.py", line 28, in <module>
    import matplotlib._png as _png
```

**Comment by stevengj** [comment]
I have the same problem running `import matplotlib.backends.backend_qt4agg` from `python`, so it seems like the Qt4Agg backend is broken in Conda on MacOS.  😢

**Comment by stevengj** [comment]
Seems to be related to conda-forge/libpng-feedstock#10

**Comment by stevengj** [comment]
Okay, I got around the libpng problem by doing `Conda.rm` on `libpng` and `matplotlib` and then re-adding `matplotlib`, as [described here](http://stackoverflow.com/questions/38253546/error-importing-python-matplotlib).

**Comment by stevengj** [comment]
Okay, it works for me, now that #244 is closed.  Try it with the master PyCall *and* master PyPlot.

**Comment by ChrisRackauckas** [comment]
Same warning.

```julia
WARNING: No working GUI backend found for matplotlib
```

Both PyCall and PyPlot updated and re-compiled.

**Comment by stevengj** [comment]
Can you try it on Julia 0.5?  I haven't tested on 0.6 recently.

**Comment by ChrisRackauckas** [comment]
It kills the REPL in v0.5:

```julia
julia> using PyPlot

julia> plot(rand(4),rand(4))
This application failed to start because it could not find or load the Qt platform plugin "windows"
in "".

Reinstalling the application may fix this problem.
```

Note this is on Windows 10.

**Comment by stevengj** [comment]
@ChrisRackauckas, I can reproduce that problem (on my Windows 8 VM); it seems like an error in how Conda installed the Qt libraries...

The Qt4Agg and TkAgg backends seem to work fine, though; maybe just edit your Matplotlibrc?

**Comment by ChrisRackauckas** [comment]
where is the matplotlibrc file?

**Comment by stevengj** [comment]
`pyimport("matplotlib")["matplotlib_fname"]()`

**Comment by ChrisRackauckas** [comment]
Yes, those two backends work fine on v0.5. That's not the case for v0.5.

**Comment by musm** [comment]
I think I'm having the same issue. But perhaps though a different route. I just wasted a grand amount of time on this.

(prelude, I uninstalled Anaconda, because of HD5F.jl problems, HD5F.jl then seemed to work, but PyPlot.jl broke,   well I need PyPlot.jl so I went back and reinstalled Anaconda.) 

...Now PyPlot.jl doesn't properly work as it used to before.

The problem:  It wont' select the qt backend.  Matplotlib using Python properly select the qt backend. So I'm at a loss here
```julia
using PyCall
pygui(:qt)
using PyPlot
plot(rand(10))
```
--> gives a tk backend figure

**Comment by stevengj** [comment]
@musm, have you checked out the master versions of PyCall and PyPlot?   (You shouldn't need the `pygui` call if your matplotlibrc file is set up.)  Qt5Agg is only supported in master right now.

**Comment by musm** [comment]
I get the same error as Chris on master PyPlot and PyCall

```julia
julia> Pkg.checkout("PyCall")
INFO: Checking out PyCall master...
INFO: Pulling PyCall latest master...
INFO: No packages to install, update or remove

julia> Pkg.checkout("PyPlot")
INFO: Checking out PyPlot master...
INFO: Pulling PyPlot latest master...
INFO: No packages to install, update or remove

julia> using PyPlot

julia> Pkg.build("PyPlot")
INFO: Building PyCall
INFO: PyCall is using C:\Anaconda3\python.exe (Python 3.5.2) at C:\Anaconda3\python.exe, libpython = C:\Anaconda3\python35
INFO: C:\Users\Mus\.julia\v0.5\PyCall\deps\deps.jl has been updated
INFO: C:\Users\Mus\.julia\v0.5\PyCall\deps\PYTHON has been updated

julia> using PyPlot

julia> plot(randn(10))
This application failed to start because it could not find or load the Qt platform plugin "windows"
in "".

Reinstalling the application may fix this problem.
```

FYI I installed the latest Anaconda

**Comment by musm** [comment]
Is it an odd dll problem?  

E.g: 
this is how things looks in pyplot
![image](https://cloud.githubusercontent.com/assets/4319522/19197657/020ed9a4-8c89-11e6-8dfe-a39372fb27be.png)


this is how it looks from python
![image](https://cloud.githubusercontent.com/assets/4319522/19197673/1be4ae44-8c89-11e6-8ffa-dbc4ab34d917.png)

as you can see, the backend is incorrect in PyPlot

**Comment by stevengj** [comment]
I got the same error about "could not find or load the Qt platform plugin" in Conda, but I got that error *both* with PyPlot and with trying the Qt5Agg backend in Python, and I concluded that they have a DLL problem in the latest Conda packages.   I concluded that I had to use Qt4Agg, which works fine for me.

@musm, your second message about "the backend is incorrect" makes no sense to me.  I thought you got an "application failed to start" message.  So how are you seeing the plot window at all?

**Comment by musm** [comment]
The figures are when I switch to Qt4Agg in the matplotlibrc file

**Comment by musm** [comment]
This is very strange. I have the following version of qt
```julia

# All requested packages already installed.
# packages in environment at C:\Anaconda3:
#
pyqt                      5.6.0                    py35_0
```

Now with  Qt5Agg I can plot in python but *not* using PyPlot. If I then switch to the Qt4Agg, I of course cannot plot with python because I do not have pyqt4 installed, however PyPlot *does* work in this case, maybe it's just falling back to the tk ? backend  in this case.

**Comment by stevengj** [comment]
@musm, are you sure you are using the same Python executable with Julia and when you run `python`?  Look at `using PyCall; PyCall.pyprogramname`.

Qt4Agg works with pyqt 5 via a shim layer in Matplotlib (matplotlib/matplotlib#3072).

**Comment by stevengj** [comment]
`PyPlot.backend` will tell you what backend it selected.

**Comment by musm** [comment]
```julia
julia> using PyCall; PyCall.pyprogramname
"C:\\Anaconda3\\python.exe"

julia>  PyDict(pyimport("matplotlib")["rcParams"])["backend"]
"Qt5Agg"


julia> using PyPlot

julia> PyPlot.backend
"qt5agg"

julia> plot(randn(10))
This application failed to start because it could not find or load the Qt platform plugin "windows"
in "".

Reinstalling the application may fix this problem.
```

Yep everything looks like it pulling in the correct python and correct matplitlibrc configurations.


In any case, I'll wait for fix.

**Comment by musm** [comment]
I should add that my problem occurs on v0.5 and v0.6, i.e. can't get qt backend working.
```julia
> conda install pyqt
Fetching package metadata .........
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at C:\Anaconda3:
#
pyqt                      5.6.0                    py35_0
```

**Comment by ianshmean** [comment]
I'm having a similar issue in v0.6.0

```
julia> using PyPlot
INFO: Precompiling module PyPlot.
ERROR: LoadError: InitError: UndefVarError: name not defined
 in macro expansion at /Users/IanB/.julia/v0.6/PyCall/src/exception.jl:78 [inlined]
 in pyimport(::String) at /Users/IanB/.julia/v0.6/PyCall/src/PyCall.jl:387
 in __init__() at /Users/IanB/.julia/v0.6/PyCall/src/pyinit.jl:58
 in _include_from_serialized(::String) at ./loading.jl:150
 in _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:187
 in _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:217
 in _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in require(::Symbol) at ./loading.jl:402
 in require(::Symbol) at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in include_from_node1(::String) at ./loading.jl:532
 in include_from_node1(::String) at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in include(::String) at ./sysimg.jl:14
 in include(::String) at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in anonymous at ./<missing>:2
 in eval(::Module, ::Any) at ./boot.jl:236
 in eval(::Module, ::Any) at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:248
 in _start() at ./client.jl:335
 in _start() at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
during initialization of module PyCall
while loading /Users/IanB/.julia/v0.6/PyPlot/src/PyPlot.jl, in expression starting on line 5
ERROR: Failed to precompile PyPlot to /Users/IanB/.julia/lib/v0.6/PyPlot.ji.
 in compilecache(::String) at ./loading.jl:672
 in require(::Symbol) at ./loading.jl:453
 in require(::Symbol) at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
```

**Comment by musm** [comment]
@ianshmean  no that is issue https://github.com/JuliaPy/PyPlot.jl/issues/266
just checkout master PyCall

**Comment by goldfita** [comment]
@musm I had the same problem when I updated anaconda.

> julia> PyPlot.backend
>"qt5agg"

> julia> plot(randn(10))
> This application failed to start because it could not find or load the Qt platform plugin "windows"
> in "".

Not sure if it's the same issue, but I fixed it by setting the following environment variables.  I couldn't even use the tk backend without fixing this first.

QTDIR=C:\Users\goldfing\AppData\Local\Continuum\Anaconda3\pkgs\qt-5.6.2-vc14_3
QT_QPA_PLATFORM_PLUGIN_PATH=%QTDIR%\Library\plugins\platforms\
PATH=%PATH%;%QTDIR%\Library\bin

**Comment by davidzentlermunro** [comment]
@goldfita did you set those environment variables in the julia REPL? I'm having the same issue as you and @musm

**Comment by goldfita** [comment]
@davidzentlermunro I set my windows environment variables.  Search for "env" in start if you have win10.  In Linux, it's been a long time, but I think you put it in bashrc for a local user.  Check to make sure it works in Python first.  Then check Julia.

**Comment by stevengj** [comment]
It sounds like this is a duplicate of #278.   The latest PyCall (do `Pkg.checkout`) has a workaround; I will tag it once someone confirms that it is now working.

**Comment by davidzentlermunro** [comment]
Thanks @stevengj seems to be working fine now!
