### ISSUE TITLE
scatter3D does not work in Jupyter notebook

### ISSUE THREAD

**Issue by gdkrmr** [JuliaPy/PyPlot.jl#187]
``` julia
using PyPlot
scatter3D(rand(100), rand(100), rand(100))
```

works just fine in the REPL, but fails in the Jupyter Notebook:

```
LoadError: PyError (:PyObject_Call) <type 'exceptions.AttributeError'>
AttributeError("'PathCollection' object has no attribute 'do_3d_projection'",)
```

**Comment by tbreloff** [comment]
I see the same error.  Until this is solved, you could access it through Plots (which uses PyPlot in this case):

![tmp](https://cloud.githubusercontent.com/assets/933338/12117403/9046f5d2-b38e-11e5-8075-ae520e25b9ab.png)

**Comment by gdkrmr** [comment]
works for me, thanks!!

**Comment by vection** [comment]
Hey, is there an update on this issue? Still having the problem with 2.1.1.

**Comment by stevengj** [comment]
It works for me (Julia 0.4.3 and Matplotlib 1.4.3).

**Comment by vection** [comment]
Hey steve,
thanks for your response. Upgrading matplotlib to 1.5.1 via pip worked for me too. However I am a bit confused because I also have a matplotlib version installed via homebrew.
Anyway, thanks for pointing out that it basically works with the correct matplotlib version.

**Comment by stevengj** [comment]
@vection, what matplotlib version was *not* working?

**Comment by vection** [comment]
Sorry, this is lost somewhere in my stdout dump of a closed terminal window.

**Comment by stevengj** [comment]
I'm going to close this issue unless it re-appears with a recent matplotlib version.

**Comment by lstagner** [comment]
I just ran into this issue using matplotlib v1.5.1 and PyPlot v2.1.1

**Comment by lstagner** [comment]
To reproduce in a notebook

```julia
nx = 12
ny = 10
nz = 10

x = linspace(0,60,nx)
y = linspace(-25,25,ny)
z = linspace(-25,25,nz)

x_grid = zeros(nx,ny,nz)
y_grid = zeros(nx,ny,nz)
z_grid = zeros(nx,ny,nz)

for k=1:nz 
    for j=1:ny
        for i=1:nx
            x_grid[i,j,k] = x[i]
            y_grid[i,j,k] = y[j]
            z_grid[i,j,k] = z[k]
        end
    end
end

pygui(false)
scatter3D(x_grid,y_grid,z_grid,marker=".",color="k",alpha=.5)
```

**Comment by oschulz** [comment]
I also have this issue with  matplotlib-1.5.1 (via Anaconda2-4.0.0-Linux-x86_64) and 0.4.5 (generic 64-bit Linux binary). Tested on Ubuntu-16.04 (64-bit).

**Comment by oschulz** [comment]
@stevengj: Would it be possible to reopen this issue?I ran into the same problem with a current matplotlib installed via "pip --update" on Ubuntu-12.04.

**Comment by oschulz** [comment]
I did another cross-check: I can reproduce the `has no attribute 'do_3d_projection'` problem with Anaconda 2.5.0 (matplotlib-1.5.1), but with Anaconda 2.3.0 (matplotlib-1.4.3) all is fine. I tried this with different Julia-0.4 builds on Ubuntu-14.04 and 16.04, so I guess this is really a general issue with PyPlot.jl and the current matplotlib-1.5.1. Hope this helps with diagnosis.

**Comment by oschulz** [comment]
As @tbreloff wrote, `Plots.scatter3d` with PyPlot backend seems to work fine even with matplotlib-1.5.1. Ony when `PyPlot.scatter3D` is called directly, the error occurs.
